# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: Genshin Opt
brief-intro: 原神の聖遺物の最適化ができるサイトです
baseurl: ""
url: "http://genshinopt.toyohashi.nagoya"

permalink: /:year/:month/:day/:title/

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 6

timezone: Asia/Tokyo
future: true
